/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RiscoRouteImport } from './routes/risco'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RendaPassivaRouteImport } from './routes/renda-passiva'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as AportesRouteImport } from './routes/aportes'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RiscoRoute = RiscoRouteImport.update({
  id: '/risco',
  path: '/risco',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RendaPassivaRoute = RendaPassivaRouteImport.update({
  id: '/renda-passiva',
  path: '/renda-passiva',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const AportesRoute = AportesRouteImport.update({
  id: '/aportes',
  path: '/aportes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/aportes': typeof AportesRoute
  '/carteira': typeof CarteiraRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/planejamento': typeof PlanejamentoRoute
  '/relatorios': typeof RelatoriosRoute
  '/renda-passiva': typeof RendaPassivaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risco': typeof RiscoRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/aportes': typeof AportesRoute
  '/carteira': typeof CarteiraRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/planejamento': typeof PlanejamentoRoute
  '/relatorios': typeof RelatoriosRoute
  '/renda-passiva': typeof RendaPassivaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risco': typeof RiscoRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/aportes': typeof AportesRoute
  '/carteira': typeof CarteiraRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/planejamento': typeof PlanejamentoRoute
  '/relatorios': typeof RelatoriosRoute
  '/renda-passiva': typeof RendaPassivaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risco': typeof RiscoRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/aportes'
    | '/carteira'
    | '/configuracoes'
    | '/login'
    | '/metas'
    | '/onboarding'
    | '/perfil'
    | '/planejamento'
    | '/relatorios'
    | '/renda-passiva'
    | '/reset-password'
    | '/risco'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/aportes'
    | '/carteira'
    | '/configuracoes'
    | '/login'
    | '/metas'
    | '/onboarding'
    | '/perfil'
    | '/planejamento'
    | '/relatorios'
    | '/renda-passiva'
    | '/reset-password'
    | '/risco'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/aportes'
    | '/carteira'
    | '/configuracoes'
    | '/login'
    | '/metas'
    | '/onboarding'
    | '/perfil'
    | '/planejamento'
    | '/relatorios'
    | '/renda-passiva'
    | '/reset-password'
    | '/risco'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AportesRoute: typeof AportesRoute
  CarteiraRoute: typeof CarteiraRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  LoginRoute: typeof LoginRoute
  MetasRoute: typeof MetasRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RendaPassivaRoute: typeof RendaPassivaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RiscoRoute: typeof RiscoRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risco': {
      id: '/risco'
      path: '/risco'
      fullPath: '/risco'
      preLoaderRoute: typeof RiscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renda-passiva': {
      id: '/renda-passiva'
      path: '/renda-passiva'
      fullPath: '/renda-passiva'
      preLoaderRoute: typeof RendaPassivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aportes': {
      id: '/aportes'
      path: '/aportes'
      fullPath: '/aportes'
      preLoaderRoute: typeof AportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AportesRoute: AportesRoute,
  CarteiraRoute: CarteiraRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  LoginRoute: LoginRoute,
  MetasRoute: MetasRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  RelatoriosRoute: RelatoriosRoute,
  RendaPassivaRoute: RendaPassivaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RiscoRoute: RiscoRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
